name: Scheduled Retraining

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight (adjust as needed)

jobs:
  scheduled-retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mlflow

      - name: Run Retraining Script
        env:
          MLFLOW_TRACKING_URI: "http://0.0.0.0:5001"
        run: python automationretraining.py
