name: MLflow Training CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train-and-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mlflow

    - name: Run Training Script
      env:
        MLFLOW_TRACKING_URI: "http://your-mlflow-server:5001"
      run: python train.py

    - name: Run Tests
      run: pytest test.py

    - name: Save model artifact
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: trained-model
          path: artifacts/


