name: Model Promotion CD

on:
  workflow_run:
    workflows: ["Model Training CI"]
    types:
      - completed

jobs:
  promote:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Promote model to production
        env:
          MLFLOW_TRACKING_URI: "sqlite:///mlflow.db"
        run: |
          python automation_md_registry.py  # Script to promote the model
