name: MLflow Training CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train-and-log:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install mlflow pytest

    - name: Run Training Script
      env:
        MLFLOW_TRACKING_URI: "http://localhost:5001"
      run: python train.py

    - name: Run Model Registry Update
      env:
        MLFLOW_TRACKING_URI: "http://localhost:5001"
      run: python automation_md_registry.py

    - name: Schedule Retraining Job
      env:
        MLFLOW_TRACKING_URI: "http://localhost:5001"
      run: |
        nohup python schedule_job.py &

    - name: Run Tests
      env:
        MLFLOW_TRACKING_URI: "http://localhost:5001"
      run:
        pytest test.py

